### ISSUE TITLE
customize output columns in blast_rbh?

### ISSUE THREAD

**Issue by cheberling** [peterjc/galaxy_blast#100]
I would like to be able to output query and subject sequence start and end locations, as you can do with blast itself.  But it looks like in order to allow this multiple places in the source python code would need to be changed.

Could this be implemented?  It looks like it should be a fairly simple fix for the author.

**Comment by peterjc** [comment]
Please clarify - BLAST+ tabular (or CSV) output does let you pick these columns, and the Galaxy wrapper fully supports this:

```xml
<option selected="true" value="qstart">qstart = Start of alignment in query</option>
<option selected="true" value="qend">qend = End of alignment in query</option>
<option selected="true" value="sstart">sstart = Start of alignment in subject (database hit)</option>
<option selected="true" value="send">send = End of alignment in subject (database hit)</option>
```

Corresponding command line help:

```
   Options 6, 7, and 10 can be additionally configured to produce
   a custom format specified by space delimited format specifiers.
   The supported format specifiers are:
   ...
   	    qstart means Start of alignment in query
   	      qend means End of alignment in query
   	    sstart means Start of alignment in subject
   	      send means End of alignment in subject
   ...
   When not provided, the default value is:
   'qseqid sseqid pident length mismatch gapopen qstart qend sstart send
   evalue bitscore', which is equivalent to the keyword 'std'
```

**Comment by cheberling** [comment]
Sorry, I was using your command line script **blast_rbh.py** for reciprocal best hit blast against a downloaded database, and those default output columns were not all given.  I got the following:

#A_id | B_id | A_length | B_length | A_qcovhsp | B_qcovhsp | length | pident | bitscore

It appears that these specific columns are specified in the python script as a wrapper caller to blastn or blastp, and then does some post-formatting of the raw blast output according to the same columns, so the script would need to be changed to allow other columns.

**Comment by peterjc** [comment]
Ah, I understand your question now. Why do you want these values? That might answer my next question...

Implementing this would be confusing - the qstart, qend, sstart, send values from the A vs B search will not always perfectly match the sstart, send, qstart, qend values from the B vs A search (i.e. the two alignments will not always be mirror images). So, would you want all 8 values? If you only want one set of coordinates for A and one for B, how do you pick?

The currently exported columns of alignment length, percentage identity and bit score also have this subtle problem that the A vs B and B vs A numbers may differ. Here it is simpler as they can be considered in isolation - currently I return the lower value in each case.

**Comment by cheberling** [comment]
So I'd like these values because I am trying to assess risk in our proprietary genomes by searching for antibiotic resistance genes, virulence factor genes, presence of phages, plasmids, and mobile elements.  We would like to see whether any of these features overlap in genomic location, which may constitute higher risk.  These genomes are to be submitted to the FDA as part of a drug product, so we want to know as much as we can.

I agree that it would be a tough choice to have to choose between which sets of values for A and B alignments.  Would it make sense to take whichever one results in the shorter alignment?  Or the one with the higher bit score/lower expectancy score?  It might be safest to just take all 8 values and then I could decide on a case-by-case basis.

So could we modify to report all 8?

**Comment by peterjc** [comment]
You are welcome to take this script (open source - MIT licensed) and modify it to do that (or anything else), and while I'm curious to see how it works out, I doubt I would want to incorporate the changes here. I think it is going to be too niche, and I would rather keep the ``blast_rbh.py`` simple and focused on finding reciprocal best hits.

If you wanted to stick within Galaxy and not change the code, then probably you could get to that point by running A vs B and B vs A BLAST searches, and this tool, and then doing a suitable join operation on the resulting tables - you'd want to get one row for each BLAST RBH but have loads of columns (two sets of BLAST results). Doing it this way would have the downside of duplicating the BLAST searches - perhaps https://github.com/peterjc/galaxy_blast/tree/master/tools/reciprocal_best_hits would work better in this hypothetical Galaxy pipeline (my earlier BLAST RBH tool which expects the two BLAST searches as input).

**Comment by cheberling** [comment]
Thanks for the information, I will have to take some time to think about what may work best.

**Comment by peterjc** [comment]
Ok, good luck - and thank you for the feedback. I'm going to close this now.
