### ISSUE TITLE
Tool shed installation stuck at 'setting_tool_versions'

### ISSUE THREAD

**Issue by BertBog** [peterjc/galaxy_blast#104]
Hi,

I tried to upgrade my installation of ncbi_blast_plus trough the toolshed and it is stuck at 'setting_tool_versions'. Installing / updating other tools works fine. 
I've also tried to remove everything and then install the tool but it does not work.  In this case the dependencies are installed correctly ('blast_datatypes' and 'package_blast_plus_2_5_0'). But the 'ncbi_blast_plus' installation gets stuck. I also tried to install older versions, but they had the same problem.

Do you have any idea how this can be resolved?

Best regards,
Bert

**Comment by peterjc** [comment]
Can you view the Galaxy logs while this is happening, as that ought to help. Also what version of Galaxy are you running?

Since you mentioned ``package_blast_plus_2_5_0`` does this mean you are not using BioConda for dependencies? In this case, that shouldn't be a problem - the BLAST+ wrappers still support the legacy Galaxy package system (we are still using that locally but not for much longer hopefully).

**Comment by BertBog** [comment]
Hi Peter,

We still use the legacy package system.
I managed to solve this issue by manually removing all the files from an old installation (blastdb.loc etc). 
I think this is a problem specific to our setup, as I didn't see anyone else experiencing this issue anywhere on the main Galaxy GitHub page or on bio-stars.

**Comment by peterjc** [comment]
Glad you could fix it - sadly if there are still bugs with the legacy packaging system in Galaxy, they will never be fixed now.

As our local Galaxy server is still using the legacy XML packaging system, I have deliberately left in the old dependency definitions were possible (and for BLAST+ actively added packages for the recent releases). It is good to know other people are also using this too ;)

A word of warning - Until you update your Galaxy server, be careful about updating tools, especially IUC tools, as nowadays many of the latest wrapper updates will only work with conda dependencies (the legacy packaging system dependencies are not being listed anymore).
