### ISSUE TITLE
Can I use BlastXml.merge to merge results from different parts of blast DB?

### ISSUE THREAD

**Issue by soichih** [peterjc/galaxy_blast#11]
Hi. I am curious to know.. if I can use BlastXml.merge function to merge blast results generated by running blastp in parallel using the same input query, but using different DBs generated by different parts of original DB in FASTA format.

I've seen many people running parts of input query against copy of the same DB (which I believe can be merged quite easily), but I am not sure doing the other way around is even possible (so that I can run on high-throughput-computing environment with limited memory / resource but with a _lot_ of resources)..

I appreciate your anwer / comment!

**Comment by tcfhcdg** [comment]
Hello soichih
Did you find the way to merge the BLAST xml results from different databases?
Actually I am also looking for something like that, I splited the nr database intwo two parts and then search the same query sequences against each part of the database. Now I would like to merge the results from both parts of the databases. 

It would be nice if you could please share how you end up to fix the same issue.

Thanks

**Comment by soichih** [comment]
@tcfhcdg  Yes, I've written a simple python script that can join (and sort by evalues) XML outputs.

It's been a while since I've worked on this, but I did this in 2 steps - first to merge all *blocks*, then merge all sorted blocks into a single output file

> https://github.com/soichih/osg-blast/blob/master/bin/osg-blast-merge5
> https://github.com/soichih/osg-blast/blob/master/bin/osg-blast-merge5.block.py

I hope this helps!

**Comment by tcfhcdg** [comment]
Hello Hayashi
Thank you very much for your response. I tried to merge blast xml output from different database. But I could not succeed to merge them. As a sample I attached on e of the sequence that was blasted against two database. Could you please have a look on it it this is the right format  and could be merged based on the evalue. In each of the database I have 20 HSPs and I first want to merge them and then based on the evalue would like to select only top 20 sequence. 

Bests
Tajammul


-----Original Message-----

**Comment by tcfhcdg** [comment]
Hello Hayashi
Thank you very much for your response. I tried to merge blast xml output from different database. But I could not succeed to merge them. As a sample I attached on e of the sequence that was blasted against two database. Could you please have a look on it it this is the right format  and could be merged based on the evalue. In each of the database I have 20 HSPs and I first want to merge them and then based on the evalue would like to select only top 20 sequence.

Bests
Tajammul
