### ISSUE TITLE
tool installs fine from devshed but fails to run: cannot find executable even though it is installed

### ISSUE THREAD

**Issue by bifxcore** [peterjc/galaxy_blast#118]
On fresh version of galaxy 19.01 on Mac OS Mojave, with conda:
- install ncbi_blast_plus from toolshed
- install blast databases
- install blastdb_p.loc
- restart galaxy
- blast using local database throws:

Fatal error: Exit code 127 ()
/opt/galaxy_19.01/galaxy/database/jobs_directory/000/2/tool_script.sh: line 9: blastp: command not found

the /opt/galaxy_19.01/galaxy/database/jobs_directory/000 is empty
the blastp command exists and is executable: ./database/dependencies/blast/2.5.0/iuc/package_blast_plus_2_5_0/5dd2b68c7d04/blastp*

**Comment by peterjc** [comment]
That is strange. Are you not using conda deliberately?

**Comment by bifxcore** [comment]
Hello Peter,

there is a misunderstanding, I am using conda.

Isabelle

On Jun 15, 2019, at 3:02 AM, Peter Cock <notifications@github.com<mailto:notifications@github.com>> wrote:


That is strange. Are you not using conda deliberately?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_peterjc_galaxy-5Fblast_issues_118-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DABSYZ7C27JD7GILU7TGGWDLP2S43RA5CNFSM4HYN5LG2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXYU24A-23issuecomment-2D502353264&d=DwMCaQ&c=aBkXpkKi7gN5fe5MqrMaN-VmRugaRb1IDRfSv2xVRy0&r=wji2HRc6wNj6E_iDdlTq3YKx0Qw3BSrzTMbQmNSX_Pk&m=kIu_BJj9XKgKorTBGnALneCtb3qHNvr9yJxwK3cOFnM&s=-gWPliCxqMBqYAXIC_7USVY98XmYC00X2Qgofs8LaOo&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABSYZ7G5SONMQX37OSYUMMLP2S43RANCNFSM4HYN5LGQ&d=DwMCaQ&c=aBkXpkKi7gN5fe5MqrMaN-VmRugaRb1IDRfSv2xVRy0&r=wji2HRc6wNj6E_iDdlTq3YKx0Qw3BSrzTMbQmNSX_Pk&m=kIu_BJj9XKgKorTBGnALneCtb3qHNvr9yJxwK3cOFnM&s=T43r8vsw50NneOROQAHBaLNqT5hqRuoVj4rehapGkHc&e=>.

CONFIDENTIALITY NOTICE: This e-mail message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information protected by law. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message.

**Comment by bifxcore** [comment]
I disabled the curl proxy and was able to install conda from the run.sh and now the ncbi_blast_plus tool works like a charm.

**Comment by peterjc** [comment]
Thanks for solving this and posting back with the solution.

Apologies for the confusion, I misread the list of things installed, and thought you were using the legacy tool shed dependency system.
