### ISSUE TITLE
TravisCI has broken on the dev branch

### ISSUE THREAD

**Issue by peterjc** [peterjc/galaxy_blast#120]
Looking at the TravisCI history thanks to our cron job:

Build 795 worked:
https://travis-ci.org/peterjc/galaxy_blast/builds/552875531

Build 796 to 804 failed with ``Cannot locate xUnit report``, hard to get an exact date from the TravisCI logs, three or four months ago, so about July 2019, but seems to have been fixed... now
https://travis-ci.org/peterjc/galaxy_blast/builds/555896113

Build 806 to 808 is failing with ``MessageException: Tool not found or not accessible.``
https://travis-ci.org/peterjc/galaxy_blast/jobs/576922453

Build 809 to 813 (to date) completes with failing tests, some ``JobOutputsError: Job in error state.`` and ``BLAST Database error: Database name is required.``
https://travis-ci.org/peterjc/galaxy_blast/jobs/585684579
https://travis-ci.org/peterjc/galaxy_blast/builds/597743444

and:

```
obOutputsError: History item  different than expected, difference (using diff):
( /tmp/tmphx0IeVtblastn_four_human_vs_rhodopsin.html v. /tmp/tmpB1EonStblastn_four_human_vs_rhodopsin.html )
--- local_file
+++ history_data
@@ -16,7 +16,10 @@
 
 
 
-Database: User specified sequence set (Input: rhodopsin_nucs.fasta).
+Database: User specified sequence set (Input:
+/tmp/tmprQgXwd/tmpIAL5Yb/tmpSmGl1Z/database/job_working_directory_G1
+MyfC/000/178/task_0/dataset_7e71a821-e262-4330-aa72-
+e7fcaab12a8e.dat).
            6 sequences; 10,296 total letters
 
 
@@ -328,7 +331,10 @@
 Effective search space used: 1049670
 
 
-  Database: User specified sequence set (Input: rhodopsin_nucs.fasta).
+  Database: User specified sequence set (Input:
+/tmp/tmprQgXwd/tmpIAL5Yb/tmpSmGl1Z/database/job_working_directory_G1
+MyfC/000/178/task_0/dataset_7e71a821-e262-4330-aa72-
+e7fcaab12a8e.dat).
     Posted date:  Unknown
   Number of letters in database: 10,296
   Number of sequences in database:  6
```

The nature of the diff suggests a change in how planemo/galaxy pass the test filenames to BLAST - the test can be relaxed to allow a couple of lines of disagreement in the diff, but might hint at how everything else is breaking?

**Comment by nsoranzo** [comment]
> The nature of the diff suggests a change in how planemo/galaxy pass the test filenames to BLAST - the test can be relaxed to allow a couple of lines of disagreement in the diff

Yes, Galaxy changed how the test data files are handled, so filenames change at every planemo test run. So you need 2 more diff lines for each filename.

**Comment by peterjc** [comment]
Looks like 0a855ef45837b9baf6dc1b791cc38351f155baa6 fixed the diff issue, which was the easy bit.

**Comment by mvdbeek** [comment]
> Yes, Galaxy changed how the test data files are handled, so filenames change at every planemo test run. So you need 2 more diff lines for each filename.

Or symlinking the file to `$query.element_identifier`, if the history name is important.

**Comment by mvdbeek** [comment]
I've bisected the other errors down to https://github.com/galaxyproject/galaxy/commit/ec74687d12f0ab6ddba6e6da66df2e4ab3547d3c ... which makes me think that this is probably something that breaks the way planemo sets up the galaxy app object.

**Comment by mvdbeek** [comment]
Alright, I think this should be fixed once https://github.com/galaxyproject/galaxy/pull/8839 is merged (and merged forward to dev)

**Comment by peterjc** [comment]
Testing now with an extra job triggered on TravisCI,
https://travis-ci.org/peterjc/galaxy_blast/builds/602295628

**Comment by peterjc** [comment]
Fixed, thank you @mvdbeek
