### ISSUE TITLE
Replace TravisCI for testing

### ISSUE THREAD

**Issue by peterjc** [peterjc/galaxy_blast#140]
Probably will use Github Actions, look at IUC https://github.com/galaxyproject/tools-iuc/blob/master/.github/workflows/pr.yaml

**Comment by bernt-matthias** [comment]
https://github.com/galaxyproject/galaxy-tool-repository-template

**Comment by bernt-matthias** [comment]
Hopefully soon with https://github.com/galaxyproject/tools-iuc/pull/4830
