### ISSUE TITLE
[help] Huge Memory Consumption  For blastn

### ISSUE THREAD

**Issue by hmyh1202** [peterjc/galaxy_blast#141]
Hello sir：
    
   I used a  big blastn database for local alignment using blastn of  BLAST 2.10.1+, how can I  cut memory when using blastn ?

Thank you .

**Comment by peterjc** [comment]
BLASTN can be memory hungry, it may not be practical but can you use a smaller database? e.g. Your species of interest rather than the full NT database.

Is there any indication that the memory usage is worse via Galaxy, than if you ran BLAST directly?

**Comment by hmyh1202** [comment]
Yes， I did do the blastN directly using BLAST of&nbsp; linux version, and I will try small DB for locall alignment. Thank you. 


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "peterjc/galaxy_blast"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月21日(星期四) 下午2:47
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [peterjc/galaxy_blast] [help] Huge Memory Consumption  For blastn (Issue #141)





 
BLASTN can be memory hungry, it may not be practical but can you use a smaller database? e.g. Your species of interest rather than the full NT database.
 
Is there any indication that the memory usage is worse via Galaxy, than if you ran BLAST directly?
