### ISSUE TITLE
Write tests with *.loc databases as input

### ISSUE THREAD

**Issue by peterjc** [peterjc/galaxy_blast#53]
See also #6 for writing tests with BLAST databases via the history as inputs.

This issue is for writing unit tests using bundled (small) BLAST databases listed in (test framework only) ``test-data/*.loc`` files, which thanks to @jmchilton  has recently become possible in the Galaxy test framework using ``tool_data_table_conf.xml.test``. This will probably depend on first resolving #52.

We already have some suitable databases used as output test files for ``makeblastdb`` and ``makeprofiledb``.

See https://github.com/galaxyproject/planemo/issues/11 and https://trello.com/c/mKgUX8tH/255-handle-tool-data-table-conf-xml-test-in-the-install-and-test-framework for getting support for this in the Tool Shed. Example here: https://github.com/jmchilton/picard/commit/4df8974384081ee1bb0f97e1bb8d7f935ba09d73

**Comment by peterjc** [comment]
@jmchilton testing on the Tool Shed aside (which currently seems to be having larger problems - I'm include not to wait for this and press hread with releasing the updated BLAST+ wrappers), should the new tests using the ``test-data/blastdb*.loc`` simply work on local Galaxy installations when installing via the Tool Shed?

**Comment by jmchilton** [comment]
@peterjc No - they won't work yet. Only for planemo testing or local testing where you explicitly override the tool data table configuration to point at the sample file.

**Comment by peterjc** [comment]
Thanks @jmchilton - I thought that might be the case. Is there an open issue on Trello for extending the Tool Shed framework to allow this?

**Comment by peterjc** [comment]
e.g. https://testtoolshed.g2.bx.psu.edu/view/devteam/ncbi_blast_plus/ as of 5e9d5e536b79 gave:

```
Test runs
2015-03-18 00:23:43
Automated test environment
Tests that failed
Tool id: ncbi_blastdbcmd_info
Tool version: ncbi_blastdbcmd_info
Test: test_tool_000000 (functional.test_toolbox.TestForTool_testtoolshed.g2.bx.psu.edu/repos/devteam/ncbi_blast_plus/ncbi_blastdbcmd_info/0.1.02)
Stderr:
Traceback:
Traceback (most recent call last):
  File "/tmp/buildslave/buildbot-install-test-test-tool-shed-py27/build/test/functional/test_toolbox.py", line 268, in test_tool
    self.do_it( td )
  File "/tmp/buildslave/buildbot-install-test-test-tool-shed-py27/build/test/functional/test_toolbox.py", line 55, in do_it
    raise e
RunToolException: Error creating a job for these tool inputs - {u'type': u'error', u'data': {u'db_opts': {u'database': u'Parameter database requires a value, but has no legal values defined.'}}}
```
