### ISSUE TITLE
Stian Soiland-Reyes' review for associated paper

### ISSUE THREAD

**Issue by peterjc** [peterjc/galaxy_blast#57]
General tracking issue for code issues raised by Stian Soiland-Reyes (@stain on GitHub, soilandreyes on Twitter) while reviewing our paper *NCBI BLAST+ integrated into Galaxy* as submitted to GigaScience:

```
Stian Soiland-Reyes (Twitter: soilandreyes):
Submitted my #OpenReview of @pjacock's @galaxyproject BLAST+ paper for
@GigaScience. My apologies for being picky..
https://gist.github.com/stain/a107379fc1adbb3e392b
```

I'll file separate issues for changes to the paper itself - this is purely for the code side of things.

*Update* - preprint of paper as submitted to GigaScience is now on bioRxiv http://dx.doi.org/10.1101/014043

**Comment by peterjc** [comment]
One major issue raised was to do with installing NCBI BLAST databases. This would fall under the scope of #22, even if only to add a Galaxy Data Manager for fetching and installing the latest NCBI databases.

**Comment by peterjc** [comment]
I've filed a bug against Galaxy for the poor handling of the Tool Shed being offline which Stian hit while trying to use @bgruening's Galaxy BLAST+ Docker image: https://registry.hub.docker.com/u/bgruening/galaxy-blast/

See: https://trello.com/c/f0MWXBlM/2348-browse-valid-sheds-fails-if-toolshed-offline

**Comment by peterjc** [comment]
Stian flagged the (harmless but scary) SQLite error from ``run_tests.sh`` with SQLite as seen on TravisCI,

~~~
I have therefore not been able to verify that the supporting data
actually supports the article, beyond inspecting the Travis-CI
build logs at https://travis-ci.org/peterjc/galaxy_blast/builds ..
which except for a single error seem to be verifying the tools.
https://travis-ci.org/peterjc/galaxy_blast/builds/45137901

OperationalError: (OperationalError) unable to open database file None None
~~~

I've filed a Galaxy issue on that: https://trello.com/c/7vLsIx8q/2349-scary-run-tests-sh-error-with-sqlite

**Comment by jmchilton** [comment]
Also https://github.com/galaxyproject/planemo/issues/18. It is totally harmless but it does keep getting brought up so it needs to be addressed.

**Comment by peterjc** [comment]
Stian asked *Which version of the BLAST tool was used?*, which Galaxy already records via the ``<version_command>`` tag (available to view via the information icon for any dataset in your current history).

However, Galaxy doesn't currently check that matches the version the wrapper was expecting - which I am suggesting with https://trello.com/c/9nz482vx/2352-verify-tool-versions-match-what-was-expected

**Comment by peterjc** [comment]
The revised paper is out, and we've filed issues for the outstanding issues, so I'm going to close this now.
