### ISSUE TITLE
blast version 2.2.29+ with empty input now exits with code 1 

### ISSUE THREAD

**Issue by jj-umn** [peterjc/galaxy_blast#58]
blast used to just produce an empty output with an empty input.   But, with version 2.2.29+
given an empty input query file generates an exit code of 1 and a stderr message of: "Command line argument error: Query is Empty!"
The previous behavior was useful in workflows that partitioned inputs to multiple blast jobs and concatenated the results.   A failing job now halts the entire workflow.  
The suggestion would be to enhance the command line generation to allow the tool to skip the call to blast and generate an empty output.  Peter pointed out that the best behavior for an xml output might need to be different, perhaps just the root level tag.

**Comment by peterjc** [comment]
Bug reported to the NCBI BLAST+ team by email, blog post here: http://blastedbio.blogspot.co.uk/2015/02/ncbi-blast-rejects-zero-sequence-query-files.html

Hopefully they will fix this in the next release so that we do not need to resort to any ugly workarounds.

**Comment by peterjc** [comment]
Regarding XML output, with BLAST+ 2.2.28 it would simply produce an empty file if given no queries. So that's simple to deal with :)

**Comment by peterjc** [comment]
This was fixed in BLAST+ 2.2.31
