### ISSUE TITLE
Rename dependencies folder to packages ?

### ISSUE THREAD

**Issue by peterjc** [peterjc/galaxy_blast#62]
Following the @galaxy-iuc best practises https://github.com/galaxy-iuc/standards/blob/master/docs/best_practices/repositories.rst we should be using a ``packages/`` directory rather than the current ``dependencies/`` naming.

This would mean updating the URLs in the ``.shed.yml`` files, which we can now automatically apply to the Tool Sheds using ``planemo update``.

The only downside I can see is it could break a few existing links to the old ``dependencies/`` directory on GitHub...

**Comment by bgruening** [comment]
More consistency is always good and these tools have a high reputation!

**Comment by peterjc** [comment]
Fixed this in July, forgot to close the issue.
