### ISSUE TITLE
Add better HTML output report option

### ISSUE THREAD

**Issue by pieterlukasse** [peterjc/galaxy_blast#64]
Hi Peter, 

Last year we implemented a galaxy tool that converts BLAST XML output into a html page, similar to the graphical summary that the NCBI site provides, since it didn't exist in your current wrapper. The tool is available in the Galaxy tool shed as blast2html. The tool takes as input BLAST XML and produces a single HTML file that can be viewed directly in Galaxy. For a sample of the generated html, see http://www.googledrive.com/host/0B38hQo0Gy3fDOVcyblQyeXpGTXc. 

We would like to have better integration with your blast wrapper. Would you be interested in a pull request where we add this html as an extra output option to the blast wrapper? blast2html would then become a dependency of the wrapper. 

The existing 'html' output option could be split in something like: 'simple html report' and 'rich html report' .

**Comment by pieterlukasse** [comment]
one could also argue that this should be an option of the BLAST+ binaries, keeping the wrapper as simple as possible. However, I think this implementation is fine, as long as the BLAST XML output is stable as an output format. It also gives us more flexibility for quickly adding more improvements to the html output.

**Comment by peterjc** [comment]
My initial recommendation is for this ``blastxml`` to ``html`` converter to be a standalone tool in the Tool Shed.

Note there is now BLAST XML v2 as of BLAST+ 2.2.31, see #65.

**Comment by erasche** [comment]
@peterjc, if nothing else, it would be nice to offer a suite or the tools
together in some format.

My users love the blast2html tool, and it took me a while to discover
it/think about where I should look for something like that for them.

24. jun. 2015 05.46 skrev "Peter Cock" <notifications@github.com>:
>
> My initial recommendation is for this blastxml to html converter to be a
standalone tool in the Tool Shed.

**Comment by peterjc** [comment]
A BLAST "suite" option (making bundles of existing Tool Shed entries available as a group) has merit - especially as part of an (IUC?) effort to create various task focused suites.

**Comment by erasche** [comment]
OK, I'll add that to the todo list. :)

**Comment by lecorguille** [comment]
Hi,

I have just pushing some developments around a visualisation for Blast outputs.
After month of break on this project, I wanted to carry on to finalize what 2 students produced.
https://github.com/lecorguille/galaxy-blastvisu


But unfortunately, after a few test, it remains two issues:
- The visualisation is not propose to blastxml datatsets: https://github.com/lecorguille/galaxy-blastvisu/issues/1
- The mako need Biopython. It worked on the old dev setup but Biopython seems not available for the visualisation even if it's installed on the server: https://github.com/lecorguille/galaxy-blastvisu/issues/2

We produced a tool (Emma Prudent's work) but I believe that it could be interesting as a visualisation (Caroline Vernette's work)

**Comment by pieterlukasse** [comment]
@peterjc should I close this issue? Any updates?

**Comment by peterjc** [comment]
No news that I can think of, closing as suggested.
