### ISSUE TITLE
NotFound: cannot find 'files_path' while searching for 'db_opts.histdb.files_path'

### ISSUE THREAD

**Issue by peterjc** [peterjc/galaxy_blast#69]
Reported by email on the galaxy-dev list, see
https://lists.galaxyproject.org/pipermail/galaxy-dev/2015-July/022459.html
http://dev.list.galaxyproject.org/quot-Failure-when-preparing-job-quot-on-blastp-tc4667584.html

*Hi there*

*I'm trying to use the blastp tools from the ncbi_blast_tools, but every time I try and run a job I get the following error:*

```
Traceback (most recent call last):
  File "/net/datasrv3hs.sanbi.ac.za/cip0/software/galaxy/galaxysrv/galaxy/lib/galaxy/jobs/runners/__init__.py", line 163, in prepare_job
    job_wrapper.prepare()
  File "/net/datasrv3hs.sanbi.ac.za/cip0/software/galaxy/galaxysrv/galaxy/lib/galaxy/jobs/__init__.py", line 859, in prepare
    self.command_line, self.extra_filenames, self.environment_variables = tool_evaluator.build()
  File "/net/datasrv3hs.sanbi.ac.za/cip0/software/galaxy/galaxysrv/galaxy/lib/galaxy/tools/evaluation.py", line 422, in build
    raise e
NotFound: cannot find 'files_path' while searching for 'db_opts.histdb.files_path'
```

*This is happening when expanding the tool template. The BLAST db in in the history (thus the reference to histdb) but why can it not find this attribute?*

*Peter*

Given https://github.com/peterjc/galaxy_blast/commit/2bbbf7f361ada20bf1b5bd777fae6e0cb52c4a38 my guess was that since this used to be ``.extra_files_path`` perhaps the Galaxy was too old for ``.files_path`` to work? However, this is a recent Galaxy:

*This is release_15.07 (last commit listed is 39f6730e5f50b54f372b8c1e17d86d8936b5899f) and ncbi_blast_plus c16c30e9ad5b. So no, its not an old Galaxy.*

Pinging @bgruening and @jmchilton to comment.

**Comment by peterjc** [comment]
Is is worth asking Peter van Heusden to try editing ``ncbi_macros.xml`` to switch ``"${os.path.join($db_opts.histdb.files_path,'blastdb')}"`` to ``"${os.path.join($db_opts.histdb.extra_files_path,'blastdb')}"``?

**Comment by peterjc** [comment]
I've ask him to try the previous Tool Shed release (revision 2fe07f50a41e aka v0.1.01) which used the alternative form ``$db_opts.histdb.extra_files_path`` rather than the current ``$db_opts.histdb.files_path`` which appears to be failing.

**Comment by peterjc** [comment]
(The other) Peter confirmed by email that the previous Tool Shed release works, so it seems we may need to use ``.extra_files_path`` after all?

**Comment by jmchilton** [comment]
I feel like this is some sort of odd regression - no one should retreat back to ``extra_files_path`` - I feel like I unilaterally decided ``files_path`` was the "one correct answer" :).

Checking it out now...

**Comment by peterjc** [comment]
Thanks John - it looks like Galaxy needs some work on using ``extra_files_path`` with input files, but for now we'll go back to using ``files_path`` here and get an update to the Tool Shed.

Sadly we don't yet have any unit tests which would have caught this, see #3.

**Comment by peterjc** [comment]
TravisCI tests green, pushed v0.1.04 update to tool sheds:

* https://testtoolshed.g2.bx.psu.edu/view/devteam/ncbi_blast_plus/188d2aca045b
* https://toolshed.g2.bx.psu.edu/view/devteam/ncbi_blast_plus/b5f1f599d1fb

**Comment by bgruening** [comment]
Great! Thanks Peter, and sorry to be so silent was travelling and on workshops.
