### ISSUE TITLE
Strip NCBI identifiers from FASTA ID's

### ISSUE THREAD

**Issue by mmokrejs** [peterjc/galaxy_blast#79]
Hi Peter,
  while re-inventing something similar I just came over this/your  code and also ([https://bitbucket.org/ctb/ngs-course/src/tip/blast/find-reciprocal.py?fileviewer=file-view-default]) (see demangle_name function). It seems good idea to anticipate blast writes into its results shortened ID's because makeblastdb stripped them away.

  Maybe make that expectation configurable but I would keep it default.

  Admittedly, there are more identifiers then just "gi|", ...

**Comment by peterjc** [comment]
With the NCBI retiring GI numbers, this issue may simple go away...

**Comment by peterjc** [comment]
I think this is essentially solved as of BLAST+ 2.5.0 which switched to using the accessions by default, and then BLAST+ 2.6.0 which switched again to accession.version as the first two fields in the tabular output. That has implications for the BLAST wrappers of its own, see #93.

**Comment by peterjc** [comment]
I think we can close this...
