### ISSUE TITLE
Odd behaviour with ncbi blast+ wrapper blastdb.loc file being ignored.

### ISSUE THREAD

**Issue by Public-Health-Bioinformatics** [peterjc/galaxy_blast#80]
After installing ncbi_blast_plus (7f3c448e119b), I was trying to put an updated copy of the blasted.loc file into a fresh (month old) galaxy install's tool-data/ folder but its contents wouldn't load, or even show in Data Manager: blasted section  after a galaxy reset.  Might be related to #22 data table manager functionality?

As a workaround,  I had to instead rename the existing tool's empty blastdb.loc file:

mv /opt/research_galaxy/tool-data/toolshed.g2.bx.psu.edu/repos/devteam/ncbi_blast_plus/7f3c448e119b/blastdb.loc /opt/research_galaxy/tool-data/toolshed.g2.bx.psu.edu/repos/devteam/ncbi_blast_plus/7f3c448e119b/blastdb.loc.bak

Then a reload via reset or via "Data table registry" Data Manager: blastdb refresh icon worked, and the new database paths showed there.

Meanwhile a similar copy of the blastdb_p.loc file with some databases set up in it worked fine – both the tool's empty copy and the tool-data/ folder copy combined to make the appropriate lists in Data Manager.

Anybody seen this before?  (My little workaround I think will flop with any update of the ncbiblastplus tool.)

Cheers,

Damion

**Comment by peterjc** [comment]
I've not seen this on our production Galaxy, but that still has the BLAST+ wrappers installed manually, meaning there is only the one ``.../galaxy-dist/tooldata/blastdb.loc`` file to worry about.

We are in the process of commissioning a new Galaxy Server where I was planning to install this (and other locally written tools) via the main Tool Shed - at which point I might fall over the same issue. Right now @blankenberg can probably advise us on what you're seeing.

See also #22.

**Comment by blankenberg** [comment]
I'm not completely sure I am following the error correctly, but I'll try to recap:
 - Install blast with Data manager from Toolshed
 - try to manually add entries to a new `galaxy_root/tool-data/blastdb.loc` file
 - New entries in above file do not show up in tool?
 - They do show up when you edit `/opt/research_galaxy/tool-data/toolshed.g2.bx.psu.edu/repos/devteam/ncbi_blast_plus/7f3c448e119b/blastdb.loc `
 - However, you can add entries to the existing `galaxy_root/tool-data/blastdb_p.loc` file and they show up correctly?

The reason for this is likely that you don't have a `<table>` entry pointing to a `galaxy_root/tool-data/blastdb.loc` in config/tool_data_table_conf.xml(.sample), whereas the Galaxy distro comes with a `galaxy_root/tool-data/blastdb_p.loc` entry.

If you want to manually add items to `galaxy_root/tool-data/blastdb.loc`, you'll need to add a `<table>` entry for it to `config/tool_data_table_conf.xml`.

**Comment by peterjc** [comment]
Thanks @blankenberg. Is there anything we can do with the BLAST datatype definition to help? e.g. Will moving them back into the Galaxy core help (which seems to be the currently preferred approach from the IUC)?

**Comment by Public-Health-Bioinformatics** [comment]
Hi Daniel,

Ok, that would explain it:

> The reason for this is likely that you don't have a <table> entry pointing to a galaxy_root/tool-data/blastdb.loc in config/tool_data_table_conf.xml(.sample), whereas the Galaxy distro comes with a galaxy_root/tool-data/blastdb_p.loc entry.

Only the tool_data_table_conf.xml.sample version was there, and it had a blastdb_p.loc definition. Is it that the the .sample version's contents are actually getting loaded when the .xml version is absent? I didn't know that behaviour.

Thanks,

D.

**Comment by peterjc** [comment]
This email thread looks like the same or a very similar issue:

https://lists.galaxyproject.org/pipermail/galaxy-dev/2016-July/024635.html
https://lists.galaxyproject.org/pipermail/galaxy-dev/2016-July/024640.html
https://lists.galaxyproject.org/pipermail/galaxy-dev/2016-July/024644.html
https://lists.galaxyproject.org/pipermail/galaxy-dev/2016-August/024708.html

We're probably going to return the BLAST datatypes to the Galaxy core, which will resolve this in a different way:

https://lists.galaxyproject.org/pipermail/galaxy-dev/2016-August/024696.html
https://github.com/galaxyproject/galaxy/pull/2696

**Comment by Public-Health-Bioinformatics** [comment]
Sweet!

**Comment by peterjc** [comment]
We've been commissioning a new Galaxy server locally, and I experienced something similar with the BLAST tools installed from the Tool Shed. There was some important clues @blankenberg's comment earlier, but the good news is that the next Galaxy release will include the BLAST datatypes and the sample ``blastdb*.loc`` files pre-registered in ``config/tool_data_table_conf.xml(.sample)`` - see https://github.com/galaxyproject/galaxy/pull/2696

If you turn on debug logging, you'll also get more information about what is loaded from ``*.loc`` files which should help too -- see https://github.com/galaxyproject/galaxy/pull/3095 and https://github.com/galaxyproject/galaxy/pull/3099

**Comment by peterjc** [comment]
I think you might have fallen over an inconsistency about which of the three ``blastdb*.loc.sample`` files Galaxy included - causing inconsistent behaviour.

As of https://github.com/galaxyproject/galaxy/pull/3098 this was none of them, but shortly afterwards with https://github.com/galaxyproject/galaxy/pull/2696 all three are included as part of returning the BLAST database definitions are now back in the Galaxy core, see #75.

I'm going to close this now as I think this means the underlying issue has been resolved. If not, please reopen it.
