### ISSUE TITLE
Linux only sed command in Blast2GO tool_dependencies.xml

### ISSUE THREAD

**Issue by peterjc** [peterjc/galaxy_blast#81]
Currently https://github.com/peterjc/galaxy_blast/blob/master/tools/blast2go/tool_dependencies.xml has:

``` xml
                <action type="shell_command">
cp b2gPipe.properties Spain_2012_August.properties &amp;&amp;
sed -i "s/Dbacces.dbname=b2g_apr12/Dbacces.dbname=b2g_aug12/g" Spain_2012_August.properties &amp;&amp;
sed -i "s/Dbacces.dbhost=10.10.100.203/Dbacces.dbhost=publicdb.blast2go.com/g" Spain_2012_August.properties
                </action>
                <action type="shell_command">
cp b2gPipe.properties Spain_2011_June.properties &amp;&amp;
sed -i "s/Dbacces.dbname=b2g_apr12/Dbacces.dbname=b2g_jun11/g" Spain_2011_June.properties &amp;&amp;
sed -i "s/Dbacces.dbhost=10.10.100.203/Dbacces.dbhost=publicdb.blast2go.com/g" Spain_2011_June.properties
                </action>
```

These ``sed`` commands fail on Mac OS X.

**Comment by bgruening** [comment]
`-i.bak` should work, afaik.

**Comment by peterjc** [comment]
Thanks @bgruening - I knew this had come up on the IUC tools tool, e.g. https://github.com/galaxyproject/tools-iuc/commit/56f00142f17c0bd79a4900f803080e2f21e4745d

It is worth worrying about deleting the resulting ``*.bak`` files?

**Comment by bgruening** [comment]
I don't think so the installation happens in a temp folder and everything should be cleaned up afterwards.

btw:
@peterjc do you also need conda packages for all of the old (and new) BLAST packages?

**Comment by peterjc** [comment]
@bgruening yes please, I was meaning to look into BLAST conda packaging after sorting out checksums etc in all my current ``tool_dependencies.xml`` files.

**Comment by bgruening** [comment]
No promises, but I will note this down. Would be great if you have you in the conda team as well.

**Comment by peterjc** [comment]
Actually in this case it will leave stray ``*.bak`` files because the whole temp folder gets moved:

``` xml
<action type="move_directory_files"><source_directory>.</source_directory><destination_directory>$INSTALL_DIR/</destination_directory></action>
```

Still, that's fairly harmless.
