### ISSUE TITLE
Conda support

### ISSUE THREAD

**Issue by lecorguille** [peterjc/galaxy_blast#88]
Hi,

To be Conda ready, the only change should be to remove the `+` of the blast package name
https://github.com/peterjc/galaxy_blast/blob/master/tools/ncbi_blast_plus/ncbi_macros.xml#L10
```xml
<requirement type="package" version="2.2.31">blast+</requirement>
```

```xml
<requirement type="package" version="2.2.31">blast</requirement>
```

Or include both?
```xml
<requirement type="package" version="2.2.31">blast+</requirement>
<requirement type="package" version="2.2.31">blast</requirement>
```

**Comment by peterjc** [comment]
It is probably too later, but I'd rather Conda's naming be fixed since "blast" ought to mean the original NCBI "legacy" C BLAST implementation. Perhaps Conda never packaged that, and thus avoided the name collision?

Does Conda allow the plus in a package name?

**Comment by peterjc** [comment]
Note the BLAST and BLAST+ version numbers overlapped for some time, but at this point all the recent version numbers are unambiguously the new NCBI BLAST rewrite in C++, so its probably fine going forward. e.g. We could switch names to just "blast" for 2.3.x and 2.4.x series onwards?

**Comment by lecorguille** [comment]
conda via bioconda provide a `blast-legacy 2.2.22` 
The other versions target blast+ with the name `blast`

I already tried a + in an package name but @bgruening corrected me. 

So I also guess that we must assume that blast = blast+ since [legacy is no more supported](ftp://ftp.ncbi.nlm.nih.gov/blast/executables/legacy/README)

Meanwhile, if you want to maintain a tool_dependency like package. There are 2 solutions:
- include both packages `blast` and `blast+` in the `<requirement>`
- rename the tool_dependency [package name](https://github.com/peterjc/galaxy_blast/blob/master/packages/package_blast_plus_2_4_0/tool_dependencies.xml#L3) to `<package name="blast" version="2.4.0">`

**Comment by peterjc** [comment]
Double entries in the ``<requirement>`` tag looks confusing (unless can they be tagged as conda specific versus legacy Tool Shed package specific?).

I'm OK with switching the package name to just "blast" for something like 2.4.0 onwards.

**Comment by bgruening** [comment]
We can not easily change the naming schema anymore in Conda, sorry. There is a package called `blast-legacy`.

**Comment by nsoranzo** [comment]
> Double entries in the `<requirement>` tag looks confusing (unless can they be tagged as conda specific versus legacy Tool Shed package specific?).

See https://github.com/galaxyproject/galaxy/issues/1927 and the discussion in it.

**Comment by peterjc** [comment]
OK, as of pull request #89 (just merged), we will adopt BioConda's naming and switch from ``blast+`` to ``blast`` for version 2.5.0 onwards.

This means the same dependency declaration will work with either BioConda, or the legacy Tool Shed package XML system.

I'm leaving this issue open until I've actually created the new Tool Shed entries for ``package_blast_plus_2_5_0`` and updated the BLAST wrappers to use them.

**Comment by peterjc** [comment]
Created:

https://testtoolshed.g2.bx.psu.edu/view/iuc/package_blast_plus_2_5_0/

https://toolshed.g2.bx.psu.edu/view/iuc/package_blast_plus_2_5_0/

**Comment by peterjc** [comment]
Ah, I need to get these cached on depot.galaxyproject.org https://github.com/galaxyproject/cargo-port/pull/109

Also the Mac binaries are x64 only...

**Comment by peterjc** [comment]
Changes on master and TestToolShed, https://testtoolshed.g2.bx.psu.edu/view/devteam/ncbi_blast_plus/4dcc9429d6d2

So much needed changing for BLAST+ 2.5.0 I'd like wider testing before updating the main tool shed.

**Comment by peterjc** [comment]
Main Tool Shed updated, closing.

**Comment by bgruening** [comment]
Exciting! Thanks Peter!
