### ISSUE TITLE
Additional blastp parameters

### ISSUE THREAD

**Issue by caleb-easterly** [peterjc/galaxy_blast#91]
Hi, 

The @galaxyproteomics folks are hoping for some additional parameters in the blastp tool. Specifically, it would be good to have:

* `window_size`
* `threshold`
* `comp_based_stats`
* `gapopen` and `gapextend`

Is it possible to add these? I'm happy to help out any way I can. It seems like it might complicate the macro structure, given the scoring matrix  / `gapopen` / `gapextend` interaction. 

Thanks,

Caleb

**Comment by peterjc** [comment]
If you're familiar with Galaxy's XML macros, a pull request would be most welcome. Note many of these apply to other tools too, so ideally we'd cover all of them in one go.

e.g. Everything seems to have window size, include RPS-BLAST.

**Comment by caleb-easterly** [comment]
Great, I'll give it a shot and check in once I've made some progress.

**Comment by peterjc** [comment]
See pull request #96

**Comment by peterjc** [comment]
Closed via #96, thanks Caleb 👍
