### ISSUE TITLE
Update to BLAST+ 2.6.0 or straight to 2.7.0

### ISSUE THREAD

**Issue by nsoranzo** [peterjc/galaxy_blast#93]
https://www.ncbi.nlm.nih.gov/books/NBK131777/#_Blast_ReleaseNotes_BLAST_2_6_0_January_0_

**Comment by peterjc** [comment]
I'd noticed that, and started a Tool Shed package for people stuck with older Galaxy instances or not yet using Conda (like our internal instance):

https://github.com/peterjc/galaxy_blast/tree/master/packages/package_blast_plus_2_6_0

I need to upload that to the tool sheds still:

http://testtoolshed.g2.bx.psu.edu/view/iuc/package_blast_plus_2_6_0 (pending)
http://toolshed.g2.bx.psu.edu/view/iuc/package_blast_plus_2_6_0 (pending)

**Comment by peterjc** [comment]
Just to confirm, BioConda already has BLAST+ 2.6.0 available - https://anaconda.org/bioconda/blast/files

**Comment by peterjc** [comment]
The most visible change the NCBI have made is:

*"Change defaults for output formats 6, 7, and 10 to incorporate version in accessions."*

What this means is the default 12 columns have changed, in BLAST+ 2.6.0,

*"When not provided, the default value is: 'qaccver saccver pident length mismatch gapopen qstart qend sstart send evalue bitscore', which is equivalent to the keyword 'std'*"

Previously in BLAST+ 2.5.0,

*"When not provided, the default value is: 'qacc sacc pident length mismatch gapopen qstart qend sstart send evalue bitscore', which is equivalent to the keyword 'std'"*

This complicates our situation - what do we use as the default (old or new behaviour), and do we reorder the pick-your-own columns which would cause minor breaks for people re-running old analyses or workflows with the updated wrapper (as the Galaxy input parameters would differ)?

**Comment by peterjc** [comment]
Hmm, they actually changed this in 2.5.0 as well:

```
$ ~/bin/ncbi_blast/2.6.0+/blastp -help | grep -B 2 std
   When not provided, the default value is:
   'qaccver saccver pident length mismatch gapopen qstart qend sstart send
   evalue bitscore', which is equivalent to the keyword 'std'
```

Vs:

```
$ ~/bin/ncbi_blast/2.5.0+/blastp -help | grep -B 2 std
   When not provided, the default value is:
   'qacc sacc pident length mismatch gapopen qstart qend sstart send evalue
   bitscore', which is equivalent to the keyword 'std'
```

Historically:

```
$ ~/bin/ncbi_blast/2.4.0+/blastp -help | grep -B 2 std
   When not provided, the default value is:
   'qseqid sseqid pident length mismatch gapopen qstart qend sstart send
   evalue bitscore', which is equivalent to the keyword 'std'
$ bin/ncbi_blast/2.3.0+/blastp -help | grep -B 2 std
   When not provided, the default value is:
   'qseqid sseqid pident length mismatch gapopen qstart qend sstart send
   evalue bitscore', which is equivalent to the keyword 'std'
...
$ ~/bin/ncbi_blast/2.2.18+/blastp -help | grep -B 2 std
   When not provided, the default value is:
   'qseqid sseqid pident length mismatch gapopen qstart qend sstart send
   evalue bitscore', which is equivalent to the keyword 'std'
```

i.e. ``qseqid sseqid ...`` --> ``qacc sacc ...`` in v2.5.0 --> ``qaccver saccver ...`` in v2.6.0


So we've actually shipped a possibly surprisingly change in the recent wrapper already. Sigh.

**Comment by peterjc** [comment]
Because of the way this was implemented, our *"Tabular (standard 12 columns)"* and *"Tabular (extended 25 columns)"* will have followed the NCBI changes to the ``-outfmt 6`` defaults and the ``std`` alias:

```xml
    <token name="@BLAST_OUTPUT@">-out '$output1'
##Set the extended list here so when we add things, saved workflows are not affected
#if str($output.out_format)=="ext":
    -outfmt '6 std sallseqid score nident positive gaps ppos qframe sframe qseq sseq qlen slen salltitles'
#elif str($output.out_format)=="cols"
##Pick your own columns. Galaxy gives us it comma separated, BLAST+ wants space separated:
##TODO - Can we catch the user picking no columns and raise an error here?
#set cols = (str($output.std_cols)+","+str($output.ext_cols)+","+str($output.ids_cols)+","+str($output.misc_cols)+","+str($output.tax_cols)).replac\
e("None", "").replace(",,", ",").replace(",", " ").strip()
    -outfmt '6 $cols'
#else:
## Note do not quote this as can be '0 -html' which is really two arguments
    -outfmt $output.out_format
#end if
    </token>
```

We could easily define additional output formats to reproduce the legacy 12 columns, e.g.

```xml
            <param name="out_format" argument="-outfmt" type="select" label="Output format">
                <option value="6">Tabular (standard 12 columns now using qaccver, saccver, ...)</option>
                <option value="std_legacy">Tabular (original standard 12 columns using qseqid, qseqid, ...)</option>

                <option value="ext" selected="true">Tabular (extended 25 columns)</option>
                ...
            </param>
```

I think we need to update the pick-your-own columns interface to match the new standard 12 columns and our extended columns output.

**Comment by peterjc** [comment]
Another TODO: ``blastxml_to_tabular.py`` does not currently know how to generate ``qaccver`` and ``saccver`` (nor ``qacc`` and ``sacc`` which could be useful too given they were the defaults in BLAST 2.5.0).

**Comment by peterjc** [comment]
@nsoranzo any thoughts on the tabular output column 1 & 2 changes? Is this something that would affect you or your colleagues?

I've gone back and forth on this, the interface I setup and the way the pick-your-own columns does not allow the user to pick the order, all assumed the standard 12 columns were fixed.

We could revert the NCBI's change by explicitly asking for the original columns in the 12 column and extended 25 column output. It would mean least disruption to existing Galaxy workflows, but that runs counter to the NCBI goals in dropping the GI numbers and using their pipe-separated-identifiers less.

If we accept the change, the most backward compatible change to the pick-your-own columns may be to replace columns 1 and 2 to match the new NCBI convention, leave the existing (now duplicated) entries for ``qaccver`` and ``saccver`` in the identifier columns set, and add a final block at the end for the new legacy fields ``qseqid`` and ``sseqid``.

**Comment by nsoranzo** [comment]
Thanks for the heads-up! I'll have another look later, in the mean time let's ping my main BLAST user @anilthanki.

**Comment by nsoranzo** [comment]
2.7.0 has been released, so maybe we can skip 2.6.0 and update to the latest.

**Comment by peterjc** [comment]
I was thinking the same having read notes. BioConda in hand...
https://github.com/bioconda/bioconda-recipes/pull/6282

**Comment by peterjc** [comment]
In preparation for adding legacy ToolShed packages for BLAST+ 2.7.0,
https://github.com/galaxyproject/cargo-port/pull/134

**Comment by peterjc** [comment]
Legacy Tool Shed packages done,

https://toolshed.g2.bx.psu.edu/view/iuc/package_blast_plus_2_7_0/
https://testtoolshed.g2.bx.psu.edu/view/iuc/package_blast_plus_2_7_0/

BioConda BLAST+ 2.7.0 still pending.

**Comment by peterjc** [comment]
Hmm. One of our test cases triggers a segmentation fault in BLAST+ 2.7.0,
http://blastedbio.blogspot.com/2017/10/blast-270-segmentation-fault-with-html.html

I might focus on BLAST+ 2.6.0 for now, and hold off updating for BLAST+ 2.7.0 and wait for 2.7.1

**Comment by nsoranzo** [comment]
> I might focus on BLAST+ 2.6.0 for now, and hold off updating for BLAST+ 2.7.0 and wait for 2.7.1

Fair enough!

**Comment by peterjc** [comment]
Legacy Tool Shed packages done for BLAST+ 2.7.1 which replaced 2.7.0,

https://toolshed.g2.bx.psu.edu/view/iuc/package_blast_plus_2_7_1/
https://testtoolshed.g2.bx.psu.edu/view/iuc/package_blast_plus_2_7_1/

I have also deprecated the BLAST+ 2.7.0 package since the NCBI have withdrawn it:

https://toolshed.g2.bx.psu.edu/view/iuc/package_blast_plus_2_7_0/
https://testtoolshed.g2.bx.psu.edu/view/iuc/package_blast_plus_2_7_0/

BioConda BLAST+ 2.7.1 still pending.
