### ISSUE TITLE
Update NCBI URL for command line manual

### ISSUE THREAD

**Issue by peterjc** [peterjc/galaxy_blast#97]
We have this in the XML macros help section:

> For help with advanced options and their default values, visit the `NCBI BLAST® Command Line > Applications User Manual &lt;https://www.ncbi.nlm.nih.gov/books/NBK279675/&gt;`_.

That URL https://www.ncbi.nlm.nih.gov/books/NBK279675/ now gives error 410 Gone, which means that ``planemo lint`` is failing on our TravisCI tests.

Searching the site for *NCBI BLAST® Command Line Applications User Manual* suggests https://www.ncbi.nlm.nih.gov/books/NBK279690/ instead.

I will email the NCBI for confirmation, and request they create a redirect.

**Comment by peterjc** [comment]
Logged with the NCBI,

>The tracking number for your new ticket is #28045-274352

**Comment by caleb-easterly** [comment]
It looks like the new link is https://www.ncbi.nlm.nih.gov/books/NBK279684/ - the options for the command line applications were merged into a single appendix with some other sections. We could use the more targeted link https://www.ncbi.nlm.nih.gov/books/NBK279684/#_appendices_Options_for_the_commandline_a_ but I suppose it might be less stable.

**Comment by peterjc** [comment]
The NCBI says they're looking at getting a redirect setup for the old URL (which has been used in at least one published paper).

**Comment by peterjc** [comment]
GitHub seems to drop the trailing underscore on the link, so the section specific anchor does not work. But anyway, let's use that link...

**Comment by peterjc** [comment]
Likewise https://www.ncbi.nlm.nih.gov/books/NBK379667/ for the substitution matrices has also moved to the appendices document, but there is a redirect in place although not with the anchor:

https://www.ncbi.nlm.nih.gov/books/NBK279684/#_appendices_BLAST_Substitution_Matrices_

**Comment by peterjc** [comment]
The NCBI  now has a redirect in place https://www.ncbi.nlm.nih.gov/books/NBK279675/ --> https://www.ncbi.nlm.nih.gov/books/NBK279684/
